/* This file was automatically generated on Thu 29 Jan 2015 09:31:45 GMT from
 * source: /dls_sw/prod/R3.14.12.3/support/ethercat/4-1/etc/makeIocs/testIoc.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

